name: Context testing
on:
  - push
  - pull_request

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # will only run on 'push' event
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: eccho '${{ toJSON(job) }}'
      - name: Dump steps context
        if: failure() # this step will also run even if step before failed
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        if: always() # this step will always run
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
