name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: echo a string
        run: echo "hello yaml"
        continue-on-error: true # all next steps will continue even if this will fail
        timeout-minutes: 1
      - name: multiple script
        run: |
          node -v
          npm -v
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    needs: ['run-shell-command']
    runs-on: windows-latest
    steps:
      - name: Directory Powershel
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
