name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: node:16.14-stretch
    steps:
      - name: Log node, os version ins docker
        run: |
          node -v 
          cat /etc/os-release
