name: Matrix

on: push

jobs:
  node-version:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node_version: [6, 17, 10]
        include:
          - os: windows-latest
            node_version: 10
            is_windows_node_10: 'true'
        exclude:
          - os: ubuntu-latest
            node_version: 7
          - os: ubuntu-latest
            node_version: 10
    runs-on: ${{ matrix.os }}
    env:
      IS_WINDOWS_NODE_10: ${{ matrix.is_windows_node_10 }}
    # runs-on: ubuntu-latest
    steps:
      - name: Log Node Version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log Node Version
        run: |
          node -v
          echo $IS_WINDOWS_NODE_10
